// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UlesanneTooted;

#nullable disable

namespace UlesanneTooted.Migrations
{
    [DbContext(typeof(ToodedContext))]
    [Migration("20261009074207_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UlesanneTooted.Kategooria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kategooria_nimetus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kirjeldus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kategooriatabel", (string)null);
                });

            modelBuilder.Entity("UlesanneTooted.Toode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Hind")
                        .HasColumnType("real");

                    b.Property<int>("KategooriaId")
                        .HasColumnType("int");

                    b.Property<int>("Kogus")
                        .HasColumnType("int");

                    b.Property<string>("Pilt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Toodenimetus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KategooriaId");

                    b.ToTable("Toodetabel", (string)null);
                });

            modelBuilder.Entity("UlesanneTooted.Toode", b =>
                {
                    b.HasOne("UlesanneTooted.Kategooria", "Kategooria")
                        .WithMany("Tooded")
                        .HasForeignKey("KategooriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategooria");
                });

            modelBuilder.Entity("UlesanneTooted.Kategooria", b =>
                {
                    b.Navigation("Tooded");
                });
#pragma warning restore 612, 618
        }
    }
}
